### PR TITLE
migrate to single turf 7.1.0 library, bump gp to use geoblaze 2.8.0

### PR DESCRIPTION
**Pull request by twelch**
Need to look into new raster outputs, they've changed a bit.  Suspect vrm may still be getting enabled with geoblaze.stats() call?

### CODE REVIEW

**Comment by twelch** [comment]
All of the output changes seem to not be due to this gp bump.  If I toggle between the two versions of gp in this PR and run smoke tests, they both produce the same output.  The difference in values must have come from an earlier change in this repo and the smoke test just hadn't been updated?  Possibly migrating from turf 6.5 to 7 on the vector side.  Raster I'm not sure, maybe the study region boundaries changed a bit?

I'm very curious, @avmey if you install this PR, do you get the same smoke test output?  Let's compare next week in the lab.

**Comment by avmey** [comment]
Looking into this now. I have been regularly running the smoke tests, so nothing should be out of date there. One thing I would suggest is reimporting the datasets, as I've been seeing how high-resolution I can keep them, and so they may be out of date for you locally.

**Comment by avmey** [comment]
Seeing the same as you. On the `main` branch I reinstall node modules and run `estuaries`. No smoke test changes. Switch to this PR, `npm i`, and get smoke changes. Change to turf 7.0.0 in the PR, `npm i`, and still getting smoke changes. Switch back to the `main` branch, `npm i`, and no smoke changes again. Very strange.

**Comment by avmey** [comment]
Hm, okay, dug around some more. I'm unable to recreate the smoke test output in your PR. I continue to get the same output that the PR begins with (for example, `mpa-test`, `estuaries`, first metric value continues to be `7650.371709`, and I never get the value I'm seeing in your PR (7605.463625). I wonder if you reimport the datasources if this would solve some of the smoke test changes. Hopefully it's that straightforward. We can chat more when you get here.

**Pull request merged**
